### PR TITLE
IDebugBreakpoint wrappers

### PR DESCRIPTION
**Pull request by DrChat**
WIP for now. Just making this for visibility, in-case I get hit by a bus or something.

### CODE REVIEW

**Comment by 0vercl0k** [comment]
Sounds good and please don't get hit by a bus :)

I'm also thinking to pull the debug client logic into a separate crate; would love to collaborate if you're interested!

Cheers

**Comment by DrChat** [comment]
Yeah I'd be down; I think ultimately that would be the best move since an API wrapper would be generic enough to do so.

**Comment by DrChat** [comment]
@0vercl0k Poking to see if you created a separate crate by chance already.
I have some extra time today so I'm gonna throw it your way :)

**Comment by 0vercl0k** [comment]
All right, sorry for dropping the ball on this - I've spent some time today to set-up a private repo for now; you should have an invitation in your inbox.

I've ported the code in the `fbl_v01` branch; do you mind moving this PR over there? We can work on some basic docs & open it up?

Cheers

**Comment by DrChat** [comment]
All good! Yeah I can port my code over :)

**Pull request closed without merging**
